name: Build and Publish

on:
  push:
    branches: [main, release]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
        
    - name: Install Poetry
      run: pip install uv

    - name: Check out the code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: uv sync

    - name: Run unit tests
      run: uv run python -m unittest discover -s tests

    - name: Configure PyPI token
      if: github.ref == 'refs/heads/release'
      run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}  

    - name: Publish to PyPI for Release Branch
      if: github.ref == 'refs/heads/release'
      run: poetry publish --build
    
    - name: Build for main Branch   
      if: github.ref == 'refs/heads/main'
      run: poetry build
    
    - name: Create GitHub Release
      if: github.ref == 'refs/heads/release'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Release Artifact
      if: github.ref == 'refs/heads/release'
      uses: actions/upload-artifact@v2
      with:
        name: my-package
        path: dist/*